services:
  - type: web
    name: maxxtechxmd
    env: node
    region: oregon
    buildCommand: npm install && npm run build
    startCommand: npm run start
    disk:
      name: sessions
      mountPath: /app/sessions
      sizeGB: 1
    envVars:
      - key: NODE_VERSION
        value: "20"
